# Generated by Django 6.0.8 on 2026-08-12 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('operation_id', models.CharField(max_length=600, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('currency', models.CharField(default='RUB')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'СОЗДАН'), ('PROCESSING', 'В ПРОЦЕССЕ'), ('COMPLETED', 'ВЫПОЛНЕН'), ('REJECTED', 'ОТМЕНЕН')], max_length=25)),
                ('provider_payment_id', models.CharField(blank=True, max_length=600, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=25, null=True)),
                ('to_status', models.CharField(max_length=25)),
                ('event_id', models.BigIntegerField()),
                ('message', models.TextField()),
                ('occured_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.operation')),
            ],
        ),
    ]
